language: bash

# Use container-based infrastructure for quicker build start-up
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'

matrix:
  fast_finish: true

notifications:
  email: true
