language: bash

# Use container-based infrastructure for quicker build start-up
dist: trusty
sudo: false
before_install:
  - sudo apt-get -qq update
addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck *.bash*'

matrix:
  fast_finish: true

notifications:
  email: true
