language: bash

# Use container-based infrastructure for quicker build start-up
dist: trusty
sudo: required
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ trusty-backports universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install shellcheck -y
addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - bash -c 'shopt -s globstar; shellcheck -s bash $(find . -maxdepth 1 -type f -iname '*sh*')

matrix:
  fast_finish: true

notifications:
  email: true
