language: bash

# Use container-based infrastructure for quicker build start-up
dist: trusty
sudo: required
before_install:
  - sudo apt-get update -qq
addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - shellcheck -s bash $(find . -maxdepth 1 -type f -iname '*sh*')

matrix:
  fast_finish: true

notifications:
  email: true
